export const ATTENDEE_STATUS_INCOMPLETE = 'Incomplete';

export const PRINT_APP_HIDE_FIND_TICKET_BY_FULLNAME = 'PRINT_APP_HIDE_FIND_TICKET_BY_FULLNAME';
export const PRINT_APP_HIDE_FIND_TICKET_BY_EMAIL = 'PRINT_APP_HIDE_FIND_TICKET_BY_EMAIL';